### ISSUE TITLE
Configurator is generating zip with CRC errors

### ISSUE THREAD

**Issue by barecool** [benagricola/milo-config-rrf#8]
![Screenshot 2024-01-23 095048](https://github.com/benagricola/milo-config-rrf/assets/2767896/20f008c4-610c-47a9-b8a2-e1312b02d172)
when generating configs with configurator 
the zip file will not extract due to CRC errors

**Comment by benagricola** [comment]
Interesting. Seems like this might be an issue with fflate when passing through files (i.e. zero compression). Most recent commit should fix this by applying compression to each file.

**Comment by barecool** [comment]
seems the update made fixed it 
thanks for looking into it that fast
![Screenshot 2024-01-23 112457](https://github.com/benagricola/milo-config-rrf/assets/2767896/809379ce-26fe-4b7d-8e62-c9f0e9ebb288)
